cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "ffmpeg"
brew "httpd"
brew "mysql"
brew "php", link: false
cask "anki"
cask "beamer"
cask "igetter"
cask "kaleidoscope"
cask "skype"
cask "xee"